apiVersion: apps/v1
kind: Deployment
metadata:
  name: adidas-django-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adidas-django-auth
  template:
    metadata:
      labels:
        app: adidas-django-auth
    spec:
      containers:
        - name: adidas-django-auth
          image: us.gcr.io/sixth-loader-344609/adidas_django_auth
          command: ['/bin/bash', 'run.sh'] # runs migrations and starts the server
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: 'false'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: adidas_cluster
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-user
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-auth-db
                  key: POSTGRES_DB
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: SECRET_KEY
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-host
                  key: POSTGRES_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: adidas-django-auth-srv
spec:
  selector:
    app: adidas-django-auth
  ports:
    - name: adidas-django-auth
      protocol: TCP
      port: 4003
      targetPort: 8000
