apiVersion: apps/v1
kind: Deployment
metadata:
  name: adidas-express-sub-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adidas-express-sub
  template:
    metadata:
      labels:
        app: adidas-express-sub
    spec:
      containers:
        - name: adidas-express-sub
          image: us.gcr.io/sixth-loader-344609/adidas_express_sub
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: adidas_cluster
            - name: API_VERSION
              valueFrom:
                secretKeyRef:
                  name: api-version
                  key: API_VERSION
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-user
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-sub-db
                  key: POSTGRES_DB
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: debug
                  key: DEBUG
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: SECRET_KEY
            - name: NODE_ENV
              value: 'production'
---
apiVersion: v1
kind: Service
metadata:
  name: adidas-express-sub-srv
spec:
  selector:
    app: adidas-express-sub
  ports:
    - name: adidas-express-sub
      protocol: TCP
      port: 4001
      targetPort: 8000
