apiVersion: apps/v1
kind: Deployment
metadata:
  name: adidas-express-public-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adidas-express-public
  template:
    metadata:
      labels:
        app: adidas-express-public
    spec:
      containers:
        - name: adidas-express-public
          image: us.gcr.io/sixth-loader-344609/adidas_express_public
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: adidas_cluster
            - name: API_VERSION
              valueFrom:
                secretKeyRef:
                  name: api-version
                  key: API_VERSION
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: SECRET_KEY
            - name: NODE_ENV
              value: 'production'
---
apiVersion: v1
kind: Service
metadata:
  name: adidas-express-public-srv
spec:
  selector:
    app: adidas-express-public
  ports:
    - name: adidas-express-public
      protocol: TCP
      port: 4000
      targetPort: 8000
