apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
    - host: www.testadidas.io
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: adidas-django-auth-srv
                port:
                  number: 4003
          - path: /api/v1/(emails)|(subscriptions)|(campaigns)|(swagger)
            pathType: Prefix
            backend:
              service:
                name: adidas-express-public-srv
                port:
                  number: 4000